[section]
key = "amazon_analysis"
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#009688"  # Teal for a modern, refreshing color
backgroundColor = "#FAFAFA"  # Soft light gray background for a subtle look
secondaryBackgroundColor = "#E0E0E0"  # Light gray for secondary elements
textColor = "#212121"  # Dark gray text for better contrast and readability
font = "Roboto, sans-serif"  # Clean and modern font family (Roboto)
